### ISSUE TITLE
IllegalArgumentException when calling linkTo(methodOn(...)) on controller method with optional @RequestParam

### ISSUE THREAD

**Issue by jonasreese** [spring-projects/spring-hateoas#1003]
I have a controller method with an optional `@RequestParam`:

```
@GetMapping
fun find(@RequestParam("userId") userId: String, @RequestParam(required = false) query: String?): Mono<CollectionModel<EmbeddedWrapper>> {
    val controller = methodOn(MyController::class.java)
    return repository.find(userId, query))
        .collectList()
        .toMono()
        .flatMap { found ->
            linkTo(controller.find(userId, query)).withSelfRel()
                    .toMono()
                    .map { selfLink -> CollectionModel(listOf(EmbeddedWrappers(true).wrap(found) { "elements" }!!), selfLink) }
        }
}
```

Using the controller with a non-`null` query param throws an `IllegalArgumentException`:

```
java.lang.IllegalArgumentException: Source must be [null] if source type == [null]
	at org.springframework.util.Assert.isTrue(Assert.java:118)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:182)
	at org.springframework.hateoas.server.core.WebHandler$AnnotatedParametersParameterAccessor$BoundMethodParameter.asString(WebHandler.java:421)
	at org.springframework.hateoas.server.core.WebHandler.bindRequestParameters(WebHandler.java:212)
	at org.springframework.hateoas.server.core.WebHandler.lambda$linkTo$1(WebHandler.java:120)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345)
...
```
Checking `WebHandler.java`, I found this:

`this.parameterTypeDescriptor = TypeDescriptor.nested(parameter, parameter.isOptional() ? 1 : 0);`

The code seems to expect every optional parameter to be of type `Optional<...>`, but in this case it is a String, so there is no nested type. It works when I change the parameter to `Optional<String>`.

Using a check for Optional instead seems to be working:
`this.parameterTypeDescriptor = TypeDescriptor.nested(parameter, Optional.class.equals(parameter.getParameterType()) ? 1 : 0);`

**Comment by odrotbohm** [comment]
That should be fixed now. Feel free to give the snapshots a try!
