### ISSUE TITLE
EntityLinks returning different result on different execution of the proejct

### ISSUE THREAD

**Issue by Puspendert** [spring-projects/spring-hateoas#1076]
I am facing a very weird behavior from the Spring-Hateoas. I am getting varying `href` for the same resource on different execution. This is the  controller:
```
@RestController
@RequestMapping("/users")
@ExposesResourceFor(User.class)
public class UserController {

    private UserService userService;

    public UserController(UserService userService) {
        this.userService = userService;
    }

    @GetMapping(value = "/{userUniqueId}" + "/minimal")
    @ResponseStatus(value = HttpStatus.OK)
    public HttpEntity<UserMinimalDto> getUserMinimal(@PathVariable String userUniqueId) {
      .....
    }

    @GetMapping(value = "/{userUniqueId}/profile/minimal")
    public HttpEntity<UserProfileMinimalDto> getUserProfileMinimal(@PathVariable String userUniqueId){
        UserProfileMinimalDto userProfileMinimalDto = userService.getProfileMinimal(userUniqueId);

        return new ResponseEntity<>(userProfileMinimalDto, HttpStatus.OK);
    }

    @PutMapping(value = "/{userUniqueId}")
    @ResponseStatus(value = HttpStatus.OK)
    public HttpEntity<UserProfileMinimalDto> updateUserMinimal( @PathVariable String userUniqueId, @Valid @RequestBody UserProfileMinimalDto minimalDetails) {
     ......    
    }

    @GetMapping(value="/{userUniqueId}/companies")
    public HttpEntity<Resources<Object>> findAllCompanies(@PathVariable String userUniqueId ){
        ......          
    }
```
The service method:
```
public UserProfileMinimalDto getProfileMinimal(String userUniqueId) {

    User user = userDao.getUserProfileMinimal(userUniqueId);

    UserProfileMinimalDto userProfileMinimalDto = UserProfileMinimalMapper.INSTANCE.entityToDto(user);

    //creating _link here
    userProfileMinimalDto.add(entityLinks.linkFor(User.class, userUniqueId, "/profile", "/minimal").withSelfRel());

    return userProfileMinimalDto;
}
```
And the varying results are:
```
"self": {
            "href": "http://localhost:8085/api/v1/users/the-coder/profile/minimal"
        }

"self": {
            "href": "http://localhost:8085/api/v1/users"
        }

and many times an error: java.lang.IllegalArgumentException: Not enough variable values available to expand 'userUniqueId'
```
When does it happen: I am using Intellij IDEA as my IDE and it's a spring-boot project. Every time I restart my project from IDE, I get a varying result. Dependency is `<artifactId>spring-boot-starter-hateoas</artifactId>`
Spring boot version:
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.1.4.RELEASE</version>
</parent>
```

**Comment by gregturn** [comment]
What is the complete HAL document you get?

**Comment by Puspendert** [comment]
This is weird, this time I got `/jobs` and then I restarted the project and then I got `/users`.
```
{
    "firstName": "Puspender",
    "lastName": "t",
    "bio": "this is my bio updated",
    "lifeVision": "I am sharing my motivation with world",
    "gender": "MALE",
    "_links": {
        "self": {
            "href": "http://localhost:8085/api/v1/users/puspender-t/jobs"
        }
    }
}
```

Yes I have a controller for that also:
```
@RequestMapping(value = "/users" + "/{userUniqueId}" + "/jobs")
@ExposesResourceFor(User.class)
public class UserJobController {
```

**How does the Spring matches the URI string? How does it actually work behind the scene?**

When error:
```
java.lang.IllegalArgumentException: Not enough variable values available to expand 'userUniqueId'
	at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:367)
	at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:262)
	at org.springframework.web.util.HierarchicalUriComponents$FullPathComponent.expand(HierarchicalUriComponents.java:881)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:428)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:51)
	at org.springframework.web.util.UriComponents.expand(UriComponents.java:172)
	at org.springframework.web.util.UriComponentsBuilder.buildAndExpand(UriComponentsBuilder.java:430)
	at org.springframework.web.util.DefaultUriTemplateHandler.expandAndEncode(DefaultUriTemplateHandler.java:144)
	at org.springframework.hateoas.mvc.ControllerLinkBuilder$CustomUriTemplateHandler.expandAndEncode(ControllerLinkBuilder.java:357)
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:124)
	at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:103)
	at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:68)
	at org.springframework.hateoas.core.ControllerEntityLinks.linkFor(ControllerEntityLinks.java:118)
	at org.springframework.hateoas.core.ControllerEntityLinks.linkFor(ControllerEntityLinks.java:98)
	at org.springframework.hateoas.core.DelegatingEntityLinks.linkFor(DelegatingEntityLinks.java:51)
	at com.ofloy.api.web.hateoas.UserResourceAssembler.toResource(UserResourceAssembler.java:30)
	at com.ofloy.service.impl.UserServiceImpl.getProfileMinimal(UserServiceImpl.java:129)
	at com.ofloy.service.impl.UserServiceImpl$$FastClassBySpringCGLIB$$e0ea9c51.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.ofloy.service.impl.UserServiceImpl$$EnhancerBySpringCGLIB$$ccc7c9a3.getProfileMinimal(<generated>)
	at com.ofloy.api.web.controllers.UserController.getProfile(UserController.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Puspendert** [comment]
Why I want this type of mapping?
I am having this Entity class:
```
public class User{

    @Id
    private Integer userId;
    private String uniqueId;
    private String email;
   //others

   @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    private List<Job> jobs = new ArrayList<>();

}
```
So to create **bootiful** API I took an idea from `Spring-Data-Rest` project and saw how it would return me the HAL. For each JPA assosiation mapping SDR creates a separate path, for above mapping it would return something like:
```
{
  ...name and other details
  "_links": {
        "self": {
            "href": "http://localhost:8085/api/v1/users/puspender-t"
        }
        "jobs": {
            "href": "http://localhost:8085/api/v1/users/puspender-t/jobs"
        }
    }
}
```

**Comment by seregamorph** [comment]
@Puspendert , you probably have 2+ controllers or spring-data-rest Repositories which are bound to the same entity
`@ExposesResourceFor(User.class)` - search for this pattern
