### ISSUE TITLE
Bean class without reader method producing NullPointerException

### ISSUE THREAD

**Issue by rawfg** [spring-projects/spring-hateoas#1121]
When a response class which contains a getter without a `get` prefix (for instance `is` for boolean fields which is a default product of the Swagger Codegen) is defined, for instance:

```java
public class Hello extends RepresentationModel<Hello> {
    private Boolean extended;

    public Boolean isExtended() {
        return extended;
    }

    public void setExtended(Boolean extended) {
        this.extended = extended;
    }
}
```
and a link is being built using the ```WebMvcLinkBuilder``` utility class:
```java
hello.add(WebMvcLinkBuilder.linkTo(WebMvcLinkBuilder.methodOn(HelloController.class).sayHello()).withSelfRel());

```
```linkTo``` causes ```NullPointerException``` being thrown (part of the stack trace):
```java
java.lang.NullPointerException: null
	at org.springframework.core.annotation.AnnotationsScanner.getDeclaredAnnotations(AnnotationsScanner.java:461) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.core.annotation.AnnotationsScanner.isKnownEmpty(AnnotationsScanner.java:505) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.core.annotation.TypeMappedAnnotations.from(TypeMappedAnnotations.java:251) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.core.annotation.MergedAnnotations.from(MergedAnnotations.java:322) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.core.annotation.MergedAnnotations.from(MergedAnnotations.java:305) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.core.annotation.MergedAnnotations.from(MergedAnnotations.java:292) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.hateoas.mediatype.PropertyUtils.readerIsNotToBeIgnoredByJackson(PropertyUtils.java:233) ~[spring-hateoas-1.0.1.RELEASE.jar:1.0.1.RELEASE]
...
```

There is a small demo at https://github.com/rawfg/demo-is-javabeans. How to reproduce steps:
- Run the application and navigate to the http://localhost:8080/hello URL to observe the NPE being thrown.
- Stop the application, go to https://github.com/rawfg/demo-is-javabeans/blob/master/src/main/java/com/example/javabeans/demoisjavabeans/Hello.java#L22-L28 class and uncomment a `get` prefix getter and comment an `is` prefix getter.
- Rerun application and navigate to the http://localhost:8080/hello URL.
- There is no ```NullPointerException``` being thrown, the application behaves correctly.

**Comment by adediosf** [comment]
Same problem here. Found a temporary solution, create a Method variable with the name of the function to link and the parameters (if applied):
```
      Method resumeMtd = HelloController.class.getMethod("sayHello", String.class);
      res.add(linkTo(resumeMtd, "hi").withSelfRel());

```
Before the upgrade to 1.1.0, I could use directly in the linkTo method using methodOn as your example.

**Comment by odrotbohm** [comment]
I know that the `NullPointerException` is something we need to improve on but the underlying problem is that according to the Java Beans specification, the `is…` prefix *must only* be used for primitive `boolean`, while the box types require a `get…`-Prefix for the accessor method.

**Comment by odrotbohm** [comment]
A fix for the `NPE` is in place now both in master as well as the bugfix branch for 1.0 in the context of #1124.
