### ISSUE TITLE
Unable to render a RepresentationModel with embedded entities

### ISSUE THREAD

**Issue by piyushmor** [spring-projects/spring-hateoas#1160]
on version 1.0.2.RELEASE, the following exception is encountered and the response is `500`:

```
…
Caused by: java.lang.NoSuchMethodException: org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalLinkListSerializer.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_202]
        at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_202]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1312) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:307) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.http.converter.json.SpringHandlerInstantiator.serializerInstance(SpringHandlerInstantiator.java:90) ~[spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializerInstance(DefaultSerializerProvider.java:133) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerFromAnnotation(BasicSerializerFactory.java:489) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._constructWriter(BeanSerializerFactory.java:797) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:604) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:384) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:286) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:231) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1388) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1356) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:551) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:98) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:315) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:112) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433) ~[jackson-databind-2.10.1.jar:2.10.1]
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:921) ~[jackson-databind-2.10.1.jar:2.10.1]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:287) ~[spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        ... 114 more
```

with the following Model:
```
data class EmployeeResponse(
    val employees: List<EntityModel<EmployeeInformation>>
)

data class EmployeeInformation(
    val employeeId: String,
    val email: String? = null,
    val name: Name? = null,
    val discountAccounts: CollectionModel<EntityModel<DiscountAccount>>? = null
)

data class Name(
    val firstName: String,
    val lastName: String
)

data class DiscountAccount(
    val id: String,
    val active: Boolean,
    val countryCode: String,
    val coupons: CollectionModel<EntityModel<Coupon>>? = null
)

data class Coupon(
    val id: String,
    val code: String,
    val active: Boolean
)
```

my controller looks like this:
```
    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    fun getEmployees(
        employeeFilterCriteria: EmployeeFilterCriteria
    ): EmployeeResponse {
    listOf(
        EntityModel(
            EmployeeResponse(
                 id = "1",
                 discountAccounts=CollectionModel.wrap(
                               listOf(
                                     DiscountAccount(
                                          id= "2",
                                          coupons = .......
                                      )
                               )
                           )
            ),
            Link.valueOf("http://..../my/url")
       )
    )
}
```

**Comment by odrotbohm** [comment]
Would you mind deciding on what error you'd like to report? I just spent half an hour trying to reproduce the exception you claimed was thrown and now all of a sudden the ticket is changed to include a completely different error message.

Please provide a complete stack trace and a bit of code that actually assembles a representation model. Also, please clarify whether you see an exception or a response (even if invalid). They can't actually appear at the same time.

**Comment by piyushmor** [comment]
Hi, sorry for the trouble, I was trying a bunch of stuff, and finally landed with this issue in its current state

**Comment by piyushmor** [comment]
@odrotbohm I have updated the full stacktrace and the implementation

**Comment by odrotbohm** [comment]
Who has configured `SpringHandlerInstantiator` on the ÒbjectMapper`?

**Comment by piyushmor** [comment]
I am using the `Jackson2HalModule` in this spring boot app

**Comment by odrotbohm** [comment]
That doesn't really answer the question unfortunately. Also, if you do so, you *need* to configure the `HalHandlerInstantiator` on the `ObjectMapper`. The point being, you shouldn't need any of this. Boot auto-configures HATEOAS for proper rendering of HAL without any additional configuration.

**Comment by piyushmor** [comment]
Well, in our application, we are not doing anything manually with the `SpringHandlerInstantiator`. The only thing relevant to this could have been the jackson module in my perspective thus shared that information. So it _is_ a bug?

**Comment by piyushmor** [comment]
I tried removing the jackson module, but then it just treats everything like normal objects and renders them like normal objects instead of embedded objects. So, I am pretty sure we need to include the `Jackson2HalModule` in jackson configuration.

**Comment by odrotbohm** [comment]
As I already mentioned, you don't. Spring Boot automatically enables Spring HATEOAS so that requests asking for HAL get HAL. This is all configured by internals in Spring HATEOAS' configuration. 

If you want to use the conversion on a plain `ObjectMapper`, you *need* to configure both the module *and* the `HalHandlerInstantiator`. The former *does not* work without the latter. I'm closing this as works as designed as literally all HAL related integration tests successfully render responses. Feel free to point to a sample project reproducing thr error but as this stand it sounds like your configuration is invalid.
