### ISSUE TITLE
Potential NullPointerException in UriTemplate

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-hateoas#1165]
I've just upgraded to spring-data-rest 3.2.3.RELEASE and spring-hateoas 1.0.2.RELEASE and now I get a null-pointer exception:
```
B6288D65FFFBE27CF3A5D34F443E6D0C 2019-12-23 23:02:21,922 org.springframework.data.rest.webmvc.RepositoryRestExceptionHandler [https-jsse-nio-127.0.0.1-8112-exec-2] ERROR: null
java.lang.NullPointerException
	at org.springframework.hateoas.UriTemplate.expand(UriTemplate.java:261)
	at org.springframework.hateoas.Link.expand(Link.java:274)
	at com.nemesis.platform.module.restservices.core.processor.AbstractCatalogableResourceProcessor.lambda$process$1(AbstractCatalogableResourceProcessor.java:52)
```

My code is the following:
```
    @Override
    public EntityModel<AbstractCatalogableEntityDefinition> process(EntityModel<AbstractCatalogableEntityDefinition> resource) {

        AbstractCatalogableEntityDefinition abstractCatalogableEntityDefinition = resource.getContent();
        if (abstractCatalogableEntityDefinition != null) {
            abstractCatalogableEntityDefinition.setOnline(catalogVersionService.isCatalogableEntityInOnlineCatalogVersion(abstractCatalogableEntityDefinition));
            if (abstractCatalogableEntityDefinition.isOnline()) {
                entityLinks.linksToSearchResources(SyncStateEntityDefinition.class).getLink("findByTargetIdEquals")
                           .ifPresent(link -> resource.add(link.expand(abstractCatalogableEntityDefinition.getId()).withRel("mirrorSyncStates")));
            } else {
                entityLinks.linksToSearchResources(SyncStateEntityDefinition.class).getLink("findBySourceIdEquals")
                           .ifPresent(link -> resource.add(link.expand(abstractCatalogableEntityDefinition.getId()).withRel("mirrorSyncStates"))); // <-- line 52
            }
        }

        return resource;
    }
```
It looks like the `link` on line 52 has a `template` property with `factory` attribute which is `null`.

**Comment by ptahchiev** [comment]
Just checked and the same code works fine with 1.0.1.RELEASE and same spring-data-rest. It is only broken in 1.0.2.RELEASE
