### ISSUE TITLE
Unable to consume Hateoas resources using Traverson - getting java.lang.IllegalArgumentException: No plugin found for delimiter application/json! Registered plugins: [org.springframework.hateoas.mediatype.hal.HalLinkDiscoverer@11410bdd]

### ISSUE THREAD

**Issue by satscreate** [spring-projects/spring-hateoas#1481]
Hi Team,
Using below setup,
```
Spring - 2.4.3

<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-hateoas</artifactId>
</dependency>

<dependency>
<groupId>com.jayway.jsonpath</groupId>
<artifactId>json-path</artifactId>
</dependency>
```

**Controller:**
```
@GetMapping(path = "/sample")
	public @ResponseBody CollectionModel<PagedModel<Employee>> check() throws URISyntaxException {
		String rest = "https://****/v1/verify?page=100&size=1";
		Traverson client = new Traverson(new URI(rest), MediaTypes.HAL_JSON);
		HttpHeaders headers = new HttpHeaders();
		headers.add("Content-Type", "application/hal+json");
        headers.add("Authorization", "basic ***");
        headers.add("Accept", "*/*");
		CollectionModel<PagedModel<Employee>> employees = client //
				.follow("data") //
				.withHeaders(headers) //
				.toObject(new CollectionModelType<PagedModel<Employee>>() {});
		return employees;
	}
```
rest endpoint i am to hit using postman and i can consume below formatted results which is json,
**Rest Response trying to consume,**
```
{
  "links": {
    "next": {
      "href": "..."
    },
    "prev": {
      "href": "."
    },
    "self": {
      "href": ".."
    }
  },
  "data": [
    {
      "id": "...",
      "sample": "e24cfb2f-e51a-44d3-9204-e322a8db7ce1"
    }
  ]
}

```
But using spring controller Traverson API i am getting an error while consume the data,
```
trace=java.lang.IllegalArgumentException: No plugin found for delimiter application/json! Registered plugins: [org.springframework.hateoas.mediatype.hal.HalLinkDiscoverer@11410bdd].
	at org.springframework.plugin.core.SimplePluginRegistry.lambda$getRequiredPluginFor$2(SimplePluginRegistry.java:140)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.springframework.plugin.core.SimplePluginRegistry.getPluginFor(SimplePluginRegistry.java:167)
	at org.springframework.plugin.core.SimplePluginRegistry.getRequiredPluginFor(SimplePluginRegistry.java:140)
	at org.springframework.plugin.core.SimplePluginRegistry.getRequiredPluginFor(SimplePluginRegistry.java:126)
	at org.springframework.hateoas.client.LinkDiscoverers.getRequiredLinkDiscovererFor(LinkDiscoverers.java:73)
	at org.springframework.hateoas.client.Rels$LinkDiscovererRel.findInResponse(Rels.java:100)
	at org.springframework.hateoas.client.Traverson$TraversalBuilder.getAndFindLinkWithRel(Traverson.java:418)
	at org.springframework.hateoas.client.Traverson$TraversalBuilder.traverseToExpandedFinalUrl(Traverson.java:391)
	at org.springframework.hateoas.client.Traverson$TraversalBuilder.toObject(Traverson.java:311)
	at com.hpe.gsp.vtn.HomeController.indexxx(HomeController.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
, message=No plugin found for delimiter application/json! Registered plugins: [org.springframework.hateoas.mediatype.hal.HalLinkDiscoverer@11410bdd]., path=/vtns}]
```
How to consume the data its look like traverson not recognizing application/json ? or how do i consume HAL data (which is again a json )using traverson?

**Comment by odrotbohm** [comment]
You're client calling code arrangement is invalid. You specify Traverson to support HAL but then send an `Accept` header set to `*/*`. The server apparently responds with `application/json` which then makes it impossible for Traverson to find any links. Assuming your server works correct, avoiding setting the `Accept` header should properly trigger `application/hal+json` being sent for that.

That said, issuing a client web request while answering an incoming web request is architecturally bad practice. In the worst case this stalls your system (if the actual target system doesn't reply). In the best case you accumulate a lot of latency. So I'd strongly recommend to avoid that.
