### ISSUE TITLE
DummyInvocationUtils can't handle String return values

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-hateoas#155]
`ControllerLinkBuilder` fails at runtime if you try to use `methodOn` on a method with a return type of `String`; apparently, the cglib call in `DummyInvocationUtils#getProxyWithInterceptor` is trying to create a proxy for the return value for some reason and runs into the fact that `String` is final. This is probably a problem for all `final` data types, but I hit it with `String`. Changing the return type to `Object` made the error disappear.

In this stack trace, `myUri` is a controller handler method that is trying to grab the URI for a specified other method (`unwrapPerson`).

```
java.lang.IllegalArgumentException: Cannot subclass final class class java.lang.String
at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:446)
at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
at org.springframework.hateoas.core.DummyInvocationUtils.getProxyWithInterceptor(DummyInvocationUtils.java:165)
at org.springframework.hateoas.core.DummyInvocationUtils.access$100(DummyInvocationUtils.java:38)
at org.springframework.hateoas.core.DummyInvocationUtils$InvocationRecordingMethodInterceptor.intercept(DummyInvocationUtils.java:96)
at com.artsquare.gallery.server.rest.ScratchpadController$$EnhancerByCGLIB$$ab2c009f.unwrapPerson(<generated>)
at com.artsquare.gallery.server.rest.ScratchpadController.myUri(ScratchpadController.java:54)
```

**Comment by swps** [comment]
A better workaround here is to return a ModelAndView from your controller, rather than the string view name.

**Comment by candrews** [comment]
Another option is for the controller method to have CharSequence instead of String as the return type.

**Comment by meetshahblogs** [comment]
Another option is to return new HttpEntity with a String body, "new HttpEntity<String>"

**Comment by pcornelissen** [comment]
The same problem arises, when you have String in the method parameters:

having a signature like
```java
    public String getItem(@PathVariable UUID tenantId,
                          @PathVariable String projectPath,
                          @PathVariable Optional<String> pathSegments,
                          @RequestHeader(value = "Accept-Language", required = false) Optional<String> acceptLanguage,
                          @RequestParam("lang") Optional<String> langOverride,
                          @RequestParam("role") Optional<String> roleOverride,
                          Authentication authentication
    ) {
```
and then trying to get the link via
```java
                linkTo(methodOn(RenderPageByPathController.class)
                        .getItem(project.getTenantId(), project.getPathSegment(), Optional.of(page.getPath()),
                                Optional.empty(), Optional.empty(), Optional.empty(), null)
                ).withRel(rel);
```

in a test like this:
```java
   @Test
    void toModel() {
        EntityModel<Page> pageEntityModel = new PageResourceAssembler().toModel(
                Project.builder()
                        .tenantId(UUID.randomUUID())
                        .pathSegment("myproject")
                        .build(),
                Page.builder()
                        .language("de")
                        .path("deep/deeper/deepest")
                        .build());
        assertThat(pageEntityModel).isNotNull();
    }
```

yields

```
org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class java.lang.String: Common causes of this problem include using a final class or a non-visible class

	at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:216)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:158)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
	at org.springframework.hateoas.server.core.DummyInvocationUtils.getProxyWithInterceptor(DummyInvocationUtils.java:207)
	at org.springframework.hateoas.server.core.DummyInvocationUtils$InvocationRecordingMethodInterceptor.invoke(DummyInvocationUtils.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
...
Caused by: java.lang.IllegalArgumentException: Cannot subclass final class java.lang.String
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:653)
....
```
