### ISSUE TITLE
Duplicate key error when 2 record attribute have names ending with 'is'

### ISSUE THREAD

**Issue by reda-alaoui** [spring-projects/spring-hateoas#1636]
This bug is similar to #1402.

Let be a request payload:
```java
record Payload(@JsonProperty("fooBasis") String fooBasis, @JsonProperty("barBasis") String barBasis) {
   @JsonCreator
   Payload{}
}
```

Let be a controller:
```java
@Controller
class MyController {
  
  @GetMapping("/{id}")
  ResponseEntity<?> getById(@PathVariable("id") String id){
    return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build();
  }

  @PutMapping("/{id}")
  ResponseEntity<?> put(@PathVariable("id") String id, @RequestBody Payload payload){
    return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build();
  }

}
```

When constructing the affordance to the PUT method:
```java
linkTo(methodOn(MyController.class).getById("foo"))
    .withSelfRel()
    .andAffordance(
                    afford(methodOn(PhaseController.class).put("foo", null)));
```

It will fail with:
```java
Duplicate key  (attempted merging values org.springframework.hateoas.mediatype.PropertyUtils$Jsr303AwarePropertyMetadata@6d532813 and org.springframework.hateoas.mediatype.PropertyUtils$Jsr303AwarePropertyMetadata@4b51cb8f)
java.lang.IllegalStateException: Duplicate key  (attempted merging values org.springframework.hateoas.mediatype.PropertyUtils$Jsr303AwarePropertyMetadata@6d532813 and org.springframework.hateoas.mediatype.PropertyUtils$Jsr303AwarePropertyMetadata@4b51cb8f)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.springframework.hateoas.mediatype.TypeBasedPayloadMetadata.<init>(TypeBasedPayloadMetadata.java:46)
	at org.springframework.hateoas.mediatype.PropertyUtils.lambda$getExposedProperties$2(PropertyUtils.java:140)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at org.springframework.hateoas.mediatype.PropertyUtils.getExposedProperties(PropertyUtils.java:133)
	at org.springframework.hateoas.mediatype.Affordances$AffordanceBuilder.withInput(Affordances.java:171)
	at org.springframework.hateoas.server.core.SpringAffordanceBuilder.lambda$create$1(SpringAffordanceBuilder.java:104)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.springframework.hateoas.server.core.SpringAffordanceBuilder.lambda$create$2(SpringAffordanceBuilder.java:111)
	at org.springframework.hateoas.server.core.SpringAffordanceBuilder.getAffordances(SpringAffordanceBuilder.java:69)
	at org.springframework.hateoas.server.core.WebHandler.lambda$linkTo$0(WebHandler.java:166)
	at org.springframework.hateoas.server.core.WebHandler.linkTo(WebHandler.java:85)
	at org.springframework.hateoas.server.mvc.WebMvcLinkBuilderFactory.linkTo(WebMvcLinkBuilderFactory.java:127)
	at org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo(WebMvcLinkBuilder.java:167)
	at org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.afford(WebMvcLinkBuilder.java:186)
```

This is caused by `org.springframework.core.convert.Property#resolveName`:
```java
private String resolveName() {
		if (this.readMethod != null) { // true
			int index = this.readMethod.getName().indexOf("get"); // -1
			if (index != -1) { // false
				index += 3;
			}
			else {
				index = this.readMethod.getName().indexOf("is"); // 6
				if (index != -1) { // true
					index += 2; // 8
				}
				else {
					// Record-style plain accessor method, e.g. name()
					index = 0;
				}
			}
			return StringUtils.uncapitalize(this.readMethod.getName().substring(index)); // ""
		}
		else if (this.writeMethod != null) {
			int index = this.writeMethod.getName().indexOf("set");
			if (index == -1) {
				throw new IllegalArgumentException("Not a setter method");
			}
			index += 3;
			return StringUtils.uncapitalize(this.writeMethod.getName().substring(index));
		}
		else {
			throw new IllegalStateException("Property is neither readable nor writeable");
		}
	}
```

When the property name ends with `get` or `is`, the resolved name is an empty String. This leads to 2 properties named "" leading to the duplicate key exception. 
I was going for a PR in https://github.com/spring-projects/spring-framework/, but was blocked by https://github.com/spring-projects/spring-framework/issues/27420. Anyway, I guess this will lead to update `spring-framework` dependency in `spring-hateoas`.

**Comment by odrotbohm** [comment]
This suspiciously sounds like #1402, which we just released fixes for in 1.2.9, 1.3.4 and 1.4 M3. Would you mind giving them a try?

**Comment by reda-alaoui** [comment]
Tested with 1.3.4, it works :)
Sorry for the trouble.

**Comment by odrotbohm** [comment]
All good, happy coding! 🙃
