### ISSUE TITLE
Unable to Create Ordinary RestTemplate Bean

### ISSUE THREAD

**Issue by EarthCitizen** [spring-projects/spring-hateoas#1657]
Our application needs to create a `RestTemplate` bean unrelated to HATEOAS:

```java
@Bean
public RestTemplate restTemplate() {
    return new RestTemplate();
}
```
But `spring-hateoas` is interfering with this bean unexpectedly and unwantedly:
```
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:359) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at org.springframework.hateoas.config.WebConverters.augment(WebConverters.java:121) ~[spring-hateoas-1.3.3.jar:1.3.3]
	at org.springframework.hateoas.config.WebConverters.augmentClient(WebConverters.java:87) ~[spring-hateoas-1.3.3.jar:1.3.3]
	at org.springframework.hateoas.config.HypermediaRestTemplateConfigurer.registerHypermediaTypes(HypermediaRestTemplateConfigurer.java:47) ~[spring-hateoas-1.3.3.jar:1.3.3]
	at org.springframework.hateoas.config.RestTemplateHateoasConfiguration$HypermediaRestTemplateBeanPostProcessor.postProcessBeforeInitialization(RestTemplateHateoasConfiguration.java:73) ~[spring-hateoas-1.3.3.jar:1.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.9.jar:5.3.9]
	... 113 common frames omitted
```
When looking at `WebConverters.augment(WebConverters.java:121)`, I find this:
```java
Class<?> rootType = infos.get(0).getRootType();
```
Our application needs to disable all provided forms `HypermediaMappingInformation` to disable their `ObjectMapper` mixins, and is doing the following to do that:
```java
@EnableHypermediaSupport(type = {})
```
It would seem that `spring-hateoas` makes the incorrect assumption that there will always be at least one `HypermediaMappingInformation` defined, despite making it possible to define none.

**Comment by odrotbohm** [comment]
While this is obviously a bug, I'd love to learn more about the arrangement. Not enabling any media types in `@EHS` doesn't mean the list will have to be empty. The attribute only selects which media types of the ones shipping with Spring HATEOAS to activate. There still might be custom ones registered as simple configuration classes. While it's theoretically possible, I wonder what kind of use you make of Spring HATEOAS, if you're not actually rendering a hypermedia type in the first place.

**Comment by EarthCitizen** [comment]
@odrotbohm In a nutshell, I am using link building, but all of the Jackson mixins and `ObjectMapper` customized settings provided by this library need to be discarded. I have requirements for which those things interfere, and I need to use my own mixins for `PageModel` and `CollectionModel`. And I am fine setting this up in the global `ObjectMapper`. In my case, I don't need an `ObjectMapper` that is specific to one use case.

Initially, I was able to do this with setting `@EnableHypermediaSupport(type = {})`, and this worked until we added a `RestTemplate` bean.

I am currently able to work around the problem by implementing a `HypermediaMappingInformation` that returns JSON for the media type, and the same `ObjectMapper` that is given to it without making modifications.

**Comment by EarthCitizen** [comment]
@odrotbohm Yes, I would think so.
