### ISSUE TITLE
WebMvcLinkBuilder fails with a non-optional request parameter when calling toUriComponentsBuilder()

### ISSUE THREAD

**Issue by spstorey** [spring-projects/spring-hateoas#1826]
When using WebMvcLinkBuilder to build a link to a controller method with a non-optional request parameter, invoving toUriComponentsBuilder() fails.

Version 1.5.0 is fine, 1.5.1 has the issue.

I've created a demo here 

https://github.com/spstorey/linkissue/blob/main/src/main/java/com/example/linkissue/RootController.java

**Comment by odrotbohm** [comment]
What is the expected outcome of this? It's a *non-optional* request parameter, and you provide `null`. That doesn't really make sense, does it? You would create a link that wouldn't actually be resolved to the method it points to.

**Comment by shaunstorey** [comment]
Sorry for the delay in responding, our use case is from one resource, say the application root, to provide a navigable link to another resource. e.g.
`{    
   "_links": {
      "self": {
         "href": "https://myservice"
      },
      "myresource": {
         "href": "http://myservice/myresource?requiredparam={requiredparam}{&optionalparam}"
      }
   }
}`

I've implemented this in the example demo app. Adding the Link to a RepresentationModel works fine but pointing at that same method if you want to get the UriComponentsBuilder from the WebMvcLinkBuilder instance the new version of hateoas blows up. I think the underlaying library has changed and it no longer tolerates the {} chars. 

I get the following stack

`java.net.URISyntaxException: Illegal character in query at index 47: http://localhost:8080/myresource?requiredparam={requiredparam}
	at java.base/java.net.URI$Parser.fail(URI.java:2974) ~[na:na]
	at java.base/java.net.URI$Parser.checkChars(URI.java:3145) ~[na:na]
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3233) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3175) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
	at java.base/java.net.URI.create(URI.java:904) ~[na:na]
	at org.springframework.hateoas.server.core.LinkBuilderSupport.toUri(LinkBuilderSupport.java:122) ~[spring-hateoas-1.5.1.jar:1.5.1]
	at org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.toUriComponentsBuilder(WebMvcLinkBuilder.java:255) ~[spring-hateoas-1.5.1.jar:1.5.1]
	at com.example.linkissue.RootController.root(RootController.java:19) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.22.jar:5.3.22]`
