### ISSUE TITLE
"Cannot cast jdk.proxy3.$Proxy113" when running Spring Boot 3.2.1 and spring-hateoas 2.2.0 with Kotlin

### ISSUE THREAD

**Issue by johanhaleby** [spring-projects/spring-hateoas#2082]
I'm trying to create a spring boot project that uses spring-hateoas in Kotlin but I consistently fail and get errors such as:

```bash
java.lang.ClassCastException: Cannot cast jdk.proxy3.$Proxy113 to org.occurrent.example.domain.rps.decidermodel.web.cqrs.gameplay.GameReadModel
        at java.base/java.lang.Class.cast(Class.java:3889) ~[na:na]
        at org.springframework.hateoas.server.core.DummyInvocationUtils$InvocationRecordingMethodInterceptor.invoke(DummyInvocationUtils.java:96) ~[spring-hateoas-2.2.0.jar:2.2.0]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.0.jar:6.1.0]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.0.jar:6.1.0]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.0.jar:6.1.0]
        at org.occurrent.example.domain.rps.decidermodel.web.cqrs.gameplay.GameViewController$$SpringCGLIB$$0.showGame(<generated>) ~[classes/:na]
        at org.occurrent.example.domain.rps.decidermodel.web.cqrs.gameplay.GamePlayController.initializeNewGame(GamePlayController.kt:51) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.9.22.jar:1.9.22-release-704]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.9.22.jar:1.9.22-release-704]
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:207) ~[kotlin-reflect-1.9.22.jar:1.9.22-release-704]
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112) ~[kotlin-reflect-1.9.22.jar:1.9.22-release-704]
        at org.springframework.web.method.support.InvocableHandlerMethod$KotlinDelegate.invokeFunction(InvocableHandlerMethod.java:335) ~[spring-web-6.1.2.jar:6.1.2]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:259) ~[spring-web-6.1.2.jar:6.1.2]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190) ~[spring-web-6.1.2.jar:6.1.2]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.2.jar:6.1.2]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917) ~[spring-webmvc-6.1.2.jar:6.1.2]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829) ~[spring-webmvc-6.1.2.jar:6.1.2]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.2.jar:6.1.2]
```

To reproduce do the following:

1. Checkout my repository: `git clone git@github.com:johanhaleby/occurrent.git`
2. Switch branch: `git checkoout experiment/spring-hateoas`
3. Run install: `mvn clean install -Dmaven.test.skip=true`
4. Go into `decider-web` project: `cd example/domain/rps/decider-web`
5. Start the project: `mvn spring-boot:test-run`
6. When it has started, try making a request to the `initializeNewGame` method in `GamePlayController`: 

   ```
   curl -X PUT --location "http://localhost:8080/games/05CB9129-2212-4637-8F0B-168425BA0403" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d 'playerId=B03EB06A-2CA6-4C7A-967A-0FFE9183FAD8'
    ```

I could very well be using spring-hateoas in the wrong way since it's my first time using it with Kotlin, but I don't understand what I'm doing wrong. Here's my code:

```kotlin
class PlayGameRepresentationModel : RepresentationModel<PlayGameRepresentationModel>()

...

@PutMapping("{gameId}")
 fun initializeNewGame(@PathVariable("gameId") gameId: GameId, @RequestParam playerId: PlayerId): ResponseEntity<EntityModel<PlayGameRepresentationModel>> {
     log.info("Initializing new game (gameId=$gameId)")

     val self = linkTo<GameViewController> { showGame(gameId) } withRel IanaLinkRelations.SELF
     val selfWithAffordances = self andAffordances {
         afford<GamePlayController> { playGame(gameId, playerId, ROCK) }
     }

     val model = EntityModel.of(PlayGameRepresentationModel())
         .add(selfWithAffordances)

     val cmd = InitiateNewGame(gameId, Timestamp.now(), playerId)
     applicationService.execute(gameId, cmd, rps)

     return ResponseEntity.ok().header("Location", "/games/$gameId").body(model)
 }
```

Instead of using the Kotlin DSL, I've also tried using the normal Java API, but I get the same error:

```kotlin
val self = linkTo(methodOn(GameViewController::class.java).showGame(gameId) as Any).withSelfRel()
val selfWithAffordances = self.andAffordance(afford(methodOn(GamePlayController::class.java).playGame(gameId, playerId, ROCK)))
```

I've also tried creating an interface that the controllers implement, and then refer to this interface in `linkTo` and `afford`, but I still get the same error.

**Comment by odrotbohm** [comment]
What's the return type of `showGame(…)`? Return types of methods you want to point to for link creation need to be proxyable.

**Comment by johanhaleby** [comment]
`showGame` returns a `GameReadModel?`:

```kotlin
@Document("game")
@JsonInclude(NON_NULL)
sealed interface GameReadModel {
    @get:Id
    val gameId: GameId
    val status: GameStatus

    @TypeAlias("Initialized")
    data class Initialized(override val gameId: GameId, val initializedBy: PlayerId, override val status: GameStatus) : GameReadModel

    @TypeAlias("Ongoing")
    data class Ongoing(override val gameId: GameId, val firstMove: Move, val secondMove: Move? = null, override val status: GameStatus) : GameReadModel

    sealed interface Ended : GameReadModel {
        val firstMove: Move
        val secondMove: Move

        @TypeAlias("Tied")
        data class Tied(override val gameId: GameId, override val firstMove: Move, override val secondMove: Move, override val status: GameStatus) : Ended

        @TypeAlias("Won")
        data class Won(override val gameId: GameId, override val firstMove: Move, override val secondMove: Move, val winner: PlayerId, override val status: GameStatus) : Ended
    }
}
```

**Comment by odrotbohm** [comment]
There you go: sealed interfaces are unlikely to work as we need to create dynamic proxies for the return types at runtime. I assume to the sealing of the interface causes the proxy ending up not implementing it as the proxy type – by definition – will not be in the set of permitted types.

Can you try removing the sealing?

**Comment by johanhaleby** [comment]
Ah got it! Removing `sealed` makes it work, and I understand that it makes sense. Thank you for the clarification and for taking the time to explain it to me. Now I can continue working on the demo :)

**Comment by johanhaleby** [comment]
I have another thing, that may be related. The returned JSON looks like this:

```json
{
  "_links": {
    "self": {
      "href": "http://localhost:8080/games/05cb9129-2212-4637-8f0b-168425ba0403"
    }
  }
}
```

but because I do this:

```kotlin
 val selfWithAffordances = self andAffordances {
         afford<GamePlayController> { playGame(gameId, playerId, ROCK) }
 }
```

I would assume an affordance to "playGame" to be included in the JSON as well. I just want to make sure this is not a proxy thing as well!? `playGame` is defined like this:

```kotlin
```

**Comment by odrotbohm** [comment]
Affordances only come into play for media types that support hypermedia elements exceeding sole links. An example of that would be HAL FORMS. That would render request templates to indicate possible state transitions as documented [here](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#mediatypes.hal-forms).
