### ISSUE TITLE
Request param value with curly braces throws IllegalArgumentException

### ISSUE THREAD

**Issue by dreambrother** [spring-projects/spring-hateoas#335]
Example:
```java
@ResponseBody
@RequestMapping(value = "", method = RequestMethod.GET)
public Resources<FileResource> listFilesHal(
        @RequestParam(value = "q") String query) {
    Link self = linkTo(methodOn(FileRestController.class).listFilesHal(query)).withSelfRel();
    return new Resources<>(listFilesImpl(query), self);
}
```
If `q` contains curly braces (and it does because it's JSON) then linkTo throws
```GET http://localhost:8080/files?q={"foo": "bar"}```
```
java.lang.IllegalArgumentException: Map has no value for '"foo"'
	at org.springframework.web.util.UriComponents$MapTemplateVariables.getValue(UriComponents.java:276)
	at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:221)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:326)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:46)
	at org.springframework.web.util.UriComponents.expand(UriComponents.java:152)
	at org.springframework.web.util.UriComponentsBuilder.buildAndExpand(UriComponentsBuilder.java:302)
	at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:145)
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:135)
```

**Comment by vivin** [comment]
According to [RFC 1738](http://tools.ietf.org/html/rfc1738), curly braces are illegal in URLs, so what you have is actually not a valid URL. if your query parameter has JSON value, you should URL encode it. `"` and space are illegal as well, whereas `:` is reserved. In this case, you would end up with `GET http://localhost:8080/files?q=%7B%22foo%22%3A%20%22bar%22%7D`.

**Comment by dreambrother** [comment]
@vivin, seems spring-hateoas should do this automatically

**Comment by vivin** [comment]
Oh, my mistake. I thought that was a request coming in. This is a URL that Spring HATEOAS generates?

**Comment by dreambrother** [comment]
Parameter came as URL encoded value, then spring-mvc automatically decodes it and if I pass it to the linkTo method, it throws an exception.

**Comment by vivin** [comment]
Yeah, I'd imagine that it should urlencode it on its own.

**Comment by SingleShot** [comment]
There appears no way around this. If one encodes the query parameter, it ends up double-encoded.

An example of how we are encountering this error:

    linkTo(methodOn(SomeController.class).someMethod("id:{<123>, <456>}"))

Note this is not JSON - our domain has text with curly braces in it.

**Comment by SingleShot** [comment]
We are just gonna do a workaround for this, which is to call `methodOn` with a null value:

    linkTo(methodOn(SomeController.class).someMethod(null))

Then we call a method that knows about that particular parameters (in our case, it is called "query") and adds it into the URL manually:

    Link addQueryToLink(String query, Link link) {

      final UriComponentsBuilder builder = UriComponentsBuilder.fromUriString(link.getHref());

      if (query == null || query.isEmpty()) {
        builder.replaceQueryParam("query");
      } else {
        builder.replaceQueryParam("query", query);
      }

      return new Link(builder.build().encode().toUriString(), link.getRel());
    }

Obviously this can be improved upon, made more generic, etc. but ideally we should not have to do it.

**Comment by swps** [comment]
So, i hit this once per quarter or so, and it seems to always be a user error:  I'll annotate the request method arguments as @PathParam.  *smh*  Should be @PathVariable.  @PathVariable for the win.

fwiw

**Comment by gregturn** [comment]
I just crafted a test case that has a controller like this:

```java
	@RestController
	static class RequestParamBasedController {

		@GetMapping
		CollectionModel<FileSystemResource> listFiles(@RequestParam("q") String query) {

			Link self = linkTo(methodOn(RequestParamBasedController.class).listFiles(query)).withSelfRel();
			return CollectionModel.of(Collections.emptyList(), self);
		}
	}
```

And the tests look like this:

```java
@Test
void requestParamBasedLink() {

	Link link = linkTo(methodOn(RequestParamBasedController.class).listFiles("my search")).withSelfRel();
	assertThat(link.getHref()).isEqualTo("http://localhost?q=my%20search");
	assertThat(link.isTemplated()).isFalse();

	link = linkTo(methodOn(RequestParamBasedController.class).listFiles("{\"foo\": \"bar\"}")).withSelfRel();
	assertThat(link.getHref()).isEqualTo("http://localhost?q=%7B%22foo%22:%20%22bar%22%7D");
	assertThat(link.isTemplated()).isFalse();

	link = linkTo(methodOn(RequestParamBasedController.class).listFiles(null)).withSelfRel();
	assertThat(link.getHref()).isEqualTo("http://localhost?q={q}");
	assertThat(link.isTemplated()).isTrue();
}
```
Does this not create things properly now since #593.
