### ISSUE TITLE
Spring 4.1.5 incompatibity

### ISSUE THREAD

**Issue by JochenSchwander** [spring-projects/spring-hateoas#365]
If the link builder api is used with spring-hateoas in version 0.17.0 and  spring-webmvc in version 4.1.5 or later and there is a GET-Request with the Content-Type header set to "\*/\*" there is an IllegalArgumentException.

```
java.lang.IllegalArgumentException: 'Content-Type' cannot contain wildcard type '*'
	at org.springframework.util.Assert.isTrue(Assert.java:65) ~[spring-core-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.http.HttpHeaders.setContentType(HttpHeaders.java:538) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.http.server.ServletServerHttpRequest.getHeaders(ServletServerHttpRequest.java:131) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.util.UriComponentsBuilder.fromHttpRequest(UriComponentsBuilder.java:283) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.support.ServletUriComponentsBuilder.initFromRequest(ServletUriComponentsBuilder.java:121) ~[spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.support.ServletUriComponentsBuilder.fromContextPath(ServletUriComponentsBuilder.java:74) ~[spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.support.ServletUriComponentsBuilder.fromServletMapping(ServletUriComponentsBuilder.java:88) ~[spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.getBuilder(ControllerLinkBuilder.java:188) ~[spring-hateoas-0.17.0.RELEASE.jar:na]
	at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:119) ~[spring-hateoas-0.17.0.RELEASE.jar:na]
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:136) ~[spring-hateoas-0.17.0.RELEASE.jar:na]
```

**Comment by aheusingfeld** [comment]
Just for clarification: Do you mean the "Content-Type" or "Accept" header? Apart from this behavior being not acceptable, I don't see why a GET request would have a "Content-Type" header. Could you elaborate on your use case?

**Comment by JochenSchwander** [comment]
I mean the "Content-Type" header. Apache CXF JAX-RS Clients send this header with GET-Requests. (Even tho it doesn't make sense in my opinion)

**Comment by olivergierke** [comment]
This seems to be entirely caused by Spring Framework as we're basically calling `ServletUriComponentsBuilder.fromServletMapping(…)`. I can see the most recent 4.1.7 also rejecting wildcards for `Content-Type`.

I'd even argue that's reasonable behavior as it basically undermines the content negotiation mechanism on the request side of things. Did you bring this up with the Apache CXF guys?

**Comment by JochenSchwander** [comment]
> Did you bring this up with the Apache CXF guys?

I did not. (as I don't have an account there)

If the link builder api isn't used, Spring handles wildcards in the Content-Type for GET-requests just fine. So one could say that it's a problem with Spring HATEOAS.

**Comment by gregturn** [comment]
Content-type with a GET sounds strange. Like a corner case.

**Comment by olivergierke** [comment]
Well, no, it's not. As it's not about the LinkBuilder API, but Spring's `ServletUriComponentsBuilder` which (rightfully) rejects a wildcarded `Content-Type` header. Even if this was a `POST` request, what is a server supposed to do with that information?

I am not even saying, that – strictly speaking – we could just ignore those invalid headers in this particular case, I am just arguing that ultimately it's Sprig Framework's code an – if at all – needs to be fixed there.
