### ISSUE TITLE
AbstractMethodError in 0.18.0 and 0.19.0

### ISSUE THREAD

**Issue by Bert-R** [spring-projects/spring-hateoas#407]
I tried upgrading to 0.18.0, but that fails with this error:
```
2015-10-24 08:34:26.499 ERROR 15892 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.AbstractMethodError: com.fasterxml.jackson.databind.JsonSerializer.isEmpty(Ljava/lang/Object;)Z] with root cause

java.lang.AbstractMethodError: com.fasterxml.jackson.databind.JsonSerializer.isEmpty(Ljava/lang/Object;)Z
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:489)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1902)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:231)
        at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:186)
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:146)
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:71)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
        at org.springframework.web.servlet.mvc.method.aon.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFiplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

The same exception also occurs with version 0.19.0.

This is my `build.gradle` (test stuff omitted):
```gradle
buildscript {
	ext {
		springBootVersion = '1.2.7.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}") 
		classpath("io.spring.gradle:dependency-management-plugin:0.5.3.RELEASE")
	}
}

apply plugin: 'java'
apply plugin: "groovy"
apply plugin: 'eclipse-wtp'
apply plugin: 'idea'
apply plugin: 'spring-boot' 
apply plugin: 'io.spring.dependency-management' 
apply plugin: 'war'


war {
	baseName = 'yona-server'
	version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenCentral()
}

configurations {
	providedRuntime
}

dependencies {
	compile("org.springframework.boot:spring-boot-starter-data-jpa")
	compile("org.springframework.boot:spring-boot-starter-hateoas")
	compile("org.springframework.boot:spring-boot-starter-web")
	compile("org.springframework.hateoas:spring-hateoas:0.18.0.RELEASE")

	runtime("org.hsqldb:hsqldb") 
	providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
}

eclipse {
	classpath {
		 containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
		 containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
	}
}

task wrapper(type: Wrapper) {
	gradleVersion = '2.3'
}
```

**Comment by dschulten** [comment]
It seems you are trying to serialize a bean without any properties, apparently just a plain java.lang.Object instance. Not to fail on empty beans is a feature of jackson's serialization configuration.
I am afraid you have to customize the object mapper used by jackson, probably the halObjectMapper bean. See #333 for workarounds, it is related.

**Comment by Bert-R** [comment]
I don't think that's the case here.

I'm doing a GET implemented with this method:
```java
@RequestMapping(method = RequestMethod.GET)
@ResponseBody
public HttpEntity<Resources<GoalResource>> getAllGoals() {
	return createOKResponse(goalService.getAllGoals());
}
```

On version 0.17.0, I get this:
```json
{
    "_links":{
        "self":{
            "href":"http://localhost:8080/goals/"
        }
    }
}
```

This makes sense, as the collection inside `Resources` is empty.

If I repeat the same request with 0.18.0 or 0.19.0, I get the `AbstractMethodError`. When I enter data, the behavior is the same: with 0.17.0, the data is returned. With 0.18.0, the ``AbstractMethodError` occurs.

The issue can be reproduced very easily:
* Check out this project: https://github.com/yonadev/yona-server
* Run `gradlew run`
* Perform a GET on http://localhost:8080/goals/ This should give the JSON given above.
* Now change build.gradle to up the version for HATEOAS to 0.18.0
* Perform the same GET. This will result in the `AbstractMethodError`

**Comment by dschulten** [comment]
IIRC the jackson version changed as of 0.18.0. The technical problem is clearly that your bean contains a plain j.lang.Object instance and that this Jackson version is configured not to allow that. 

Am 29.10.2015 7:50 vorm. schrieb Bert Roos <notifications@github.com>:

I don't think that's the case here.

I'm doing a GET implemented with this method:

@RequestMapping(method = RequestMethod.GET) @ResponseBody public HttpEntity<Resources<GoalResource>> getAllGoals() { return createOKResponse(goalService.getAllGoals()); }

On version 0.17.0, I get this:

{ "_links":{ "self":{ "href":"http://localhost:8080/goals/" } } }

This makes sense, as the collection inside Resources is empty.

If I repeat the same request with 0.18.0 or 0.19.0, I get the AbstractMethodError. When I enter data, the behavior is the same: with 0.17.0, the data is returned. With 0.18.0, the `AbstractMethodError occurs.

The issue can be reproduced very easily:

Check out this project: https://github.com/yonadev/yona-server Run gradlew run Perform a GET on http://localhost:8080/goals/ This should give the JSON given above.Now change build.gradle to up the version for HATEOAS to 0.18.0Perform the same GET. This will result in the AbstractMethodError

**Comment by Bert-R** [comment]
To make clear that my bean does not contain a plan `java.lang.Object`, I have create a repro controller, see [this class](https://github.com/yonadev/yona-server/blob/master/src/main/java/nu/yona/server/goals/rest/ReproController.java).

To reproduce the issue:
* Check out this project: https://github.com/yonadev/yona-server
* Run `gradlew run`
* Perform a GET on http://localhost:8080/repro/ This gives the following JSon:
```json
{
    "_links":{
        "self":{
            "href":"http://localhost:8080/repro/"
        }
    }
}
```
* Now change build.gradle to up the version for HATEOAS to 0.18.0
* Perform the same GET. This will result in the `AbstractMethodError`

**Comment by dschulten** [comment]
You are right, the problem is not an empty object in your Resource. When I try to reproduce, the AbstractMethodError occurs for Jackson2HalModule$HalLinkListSerializer.isEmpty(), i.e. the HalLinkListSerializer instance has no implementation for it. Hence the code tries to call an abstract method which is defined on JsonSerializer since Jackson 2.0. However, the isEmpty signature has changed in Jackson 2.5 and does not work with the one from 2.4.6. and older. See also the commit https://github.com/spring-projects/spring-hateoas/commit/4e1e5ed934953aabcf5490d96d7ac43c88bc1d60

Apparently you have to force Jackson 2.5 or use a spring-hateoas version which contains the commit above.

**Comment by Bert-R** [comment]
That fixes it. Thanks a lot!
