### ISSUE TITLE
ControllerLinkBuilder.linkTo throws error if called outside of the context of a HTTP request

### ISSUE THREAD

**Issue by nickgrealy** [spring-projects/spring-hateoas#408]
### Current Behaviour

Given the latest spring hateos dependency `org.springframework.hateoas:spring-hateoas:0.19.0.RELEASE`,

When I attempt to use the `ControllerLinkBuilder.linkTo` method (outside of the context of a HTTP request),

``` Java
String url = ControllerLinkBuilder.linkTo(
        methodOn(GreetingController.class).greeting("Nick"))
        .toUri().toString();
```

Then I get the following exception:

```
Exception in thread "main" java.lang.IllegalStateException: Could not find current request via RequestContextHolder
    at org.springframework.util.Assert.state(Assert.java:385)
    at org.springframework.hateoas.mvc.ControllerLinkBuilder.getCurrentRequest(ControllerLinkBuilder.java:234)
    at org.springframework.hateoas.mvc.ControllerLinkBuilder.getBuilder(ControllerLinkBuilder.java:186)
    at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:117)
    at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:135)
```
### Proposed Behaviour

Instead of the exception, I'd expect to receive a relative URL (preferably including the context-path).

e.g. Instead of `http://localhost:8080/myappscontext/mycontroller/mymethod/pathvar/foo?a=1`, I'd receive `/myappscontext/mycontroller/mymethod/pathvar/foo?a=1`

Additionally, it'd be excellent if I could specify my own `UriComponentsBuilder` to be used for building the URI.

e.g.

``` Java
String url = ControllerLinkBuilder.linkTo(UriComponentsBuilder.
        fromUriString("http://myproxy.com.au/"), 
        methodOn(GreetingController.class).greeting("Nick"))
        .toUri().toString();
```
### Related

The solution proposed should (at least partially) also address these similar issues:
-  Support for relative href links? #330 
-  Customize ControllerLinkBuilder #143 
- Expose Configuration for ControllerLinkBuilder #400

**Comment by mahmoudimus** [comment]
:+1: super useful
