### ISSUE TITLE
Compatibility with Jackson 2.7

### ISSUE THREAD

**Issue by sylvainlaurent** [spring-projects/spring-hateoas#438]
Spring HATEOAS 0.19.0 is not compatible with Jackson 2.7.2 :

> Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase: method <init>(Ljava/lang/Class;)V not found
	at org.springframework.hateoas.hal.Jackson2HalModule$HalLinkListDeserializer.<init>(Jackson2HalModule.java:519)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)

It seems that the constructor that was removed was deprecated since Jackson 2.3...
see https://github.com/FasterXML/jackson-databind/commit/a5301ba825a33f95ca9749655d2ccf67c0f512a3#diff-431839367c5eccdcd048960395c0782d

**Comment by gregturn** [comment]
@sylvainlaurent Have you tested this patch against both Jackson 2.6 and 2.7? Backwards compatibility is a real bug bear with Jackson and something to watch out for.

**Comment by sylvainlaurent** [comment]
seems to be OK with both as far as I could test

**Comment by philwebb** [comment]
Any chance this can be considered soon? It's currently a blocker for Boot 1.4

**Comment by MHarris021** [comment]
+1

**Comment by olivergierke** [comment]
Duplicated by #455.
