### ISSUE TITLE
ControllerLinkBuilderFactory should include all system properties when building a link

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-hateoas#495]
According to spring mvc it is perfectly normal to have a `@RequestMapping` that looks like this:

````
@RequestMapping(value = "${spring.data.rest.base-path}/markup")
````

However when I try to create a link to this controller's method:
````
2016-09-22 12:20:15,512 org.springframework.data.rest.webmvc.RepositoryRestExceptionHandler [https-jsse-nio-127.0.0.1-8112-exec-6] ERROR: Map has no value for 'spring.data.rest.base-path'
java.lang.IllegalArgumentException: Map has no value for 'spring.data.rest.base-path'
	at org.springframework.web.util.UriComponents$MapTemplateVariables.getValue(UriComponents.java:306)
	at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:230)
	at org.springframework.web.util.HierarchicalUriComponents$FullPathComponent.expand(HierarchicalUriComponents.java:687)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:329)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:47)
	at org.springframework.web.util.UriComponents.expand(UriComponents.java:152)
	at org.springframework.web.util.UriComponentsBuilder.buildAndExpand(UriComponentsBuilder.java:348)
	at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:150)
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:172)
````

I also tried adding the property as a FRAGMENT, SEGMENT, REQUEST_PARAM or PATH_VARIABLE:
````
resource.add(linkTo(methodOn(MarkupController.class, new TemplateVariable(repositoryRestProperties.getBasePath(),                                                                                  TemplateVariable.VariableType.FRAGMENT)).getAllEntityMarkups()).withRel(
                        "markup"));
````

unfortunately the produced JSON is:
````
    "markup" : {
      "href" : "https://localhost:8112/storefront$%7B%23/rest%7D/markup/"
    },
````

**Comment by Chrisposure** [comment]
Problem is that the UriComponents does only expand the curley brackets. Leaving the $ as is.

I know this is by far a bad workaround, but it works:

```
@Value("${spring.data.rest.basePath}")
private String basePath;

@Override
public RepositoryLinksResource process(final RepositoryLinksResource resource) {
                     resource.add(new Link(ControllerLinkBuilder
				.linkTo(MyController.class, basePath)
				.withRel("relName").getHref().replace("$/", ""), "relName"));
}
```

**Comment by ywt222** [comment]
@Chrisposure yea, this can solve this problem, but it seems a little ugly, I am wondering if @olivergierke has made some progress on this?

**Comment by olivergierke** [comment]
Unrelated to Spring HATEOAS but you don't need to pull that configuration value into your mapping. Using `@BasePathAwareController` automatically prepends that.

**Comment by Josef-Reichardt** [comment]
+1
