### ISSUE TITLE
ControllerLinkBuilder does not work with "@GetMapping" and others

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-hateoas#513]
Given 

```java
@RestController
@RequiredArgsConstructor
public class ServiceEndpoint {
@GetMapping(path = "/bundeslaender/{nummer}", produces = "application/hal+json")
    public Bundesland bundesland(@PathVariable final String nummer) {
        return this.bundeslandRepository.findOneByNummer(nummer).orElseThrow(BundeslandNotFoundException::new);
    }
}
```

And the following call to ControllerLinkBuilder

```java
final List<Bundesland> bundeslaender;
bundeslaender.forEach(b -> b.add(
linkTo(methodOn(ServiceEndpoint.class).bundesland(b.getNummer())).withSelfRel())
);
```

the `linkTo` fails with

```
java.lang.IllegalArgumentException: 'uriTemplate' must not be null
	at org.springframework.util.Assert.hasText(Assert.java:168) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.util.UriTemplate.<init>(UriTemplate.java:61) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
```

It works with RequestMapping.

Versions:

```
[INFO] +- org.springframework.boot:spring-boot-starter-hateoas:jar:1.4.2.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:1.4.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.4.2.RELEASE:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.6:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.6:compile
[INFO] |  |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.6:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.3.3:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.4:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.4:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.4:compile
[INFO] |  |  +- org.springframework:spring-web:jar:4.3.4.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-webmvc:jar:4.3.4.RELEASE:compile
[INFO] |  +- org.springframework.hateoas:spring-hateoas:jar:0.20.0.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-aop:jar:4.3.4.RELEASE:compile
[INFO] |  \- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
```

**Comment by olivergierke** [comment]
Duplicates #471.

**Comment by michael-simons** [comment]
Sorry, Oliver! I should really learn to search also the closed issues…

**Comment by olivergierke** [comment]
Absolutely no problem. I constantly get caught by this as well :).
