### ISSUE TITLE
links vs _links

### ISSUE THREAD

**Issue by gehreleth** [spring-projects/spring-hateoas#690]
(spring 1.5.9)

I'm using both `@RepositoryRestResource` and regular `@RestControllers` returning instances of entities extending `ResouceSupport`. I've noticed that CRUD methods provided by repositories are exposing links as 'links' field while former ones expose them as '_links'. How to make then expose links in more consistent way?

UPD: If i return my entities via Collections.singletonList(), `links` field seem to have correct name.

**Comment by gregturn** [comment]
Show me a controller.

**Comment by gehreleth** [comment]
```
@RestController
@RequestMapping("/api/lazy-tree")
public class LazyTree {
  @Autowired
  private EntityLinks entityLinks;

  @Autowired
  private IStorageNodeRepository storageNodeRepository;

  @Bean
  public ResourceProcessor<Resource<StorageNode>> storageNodeProcessor() {
    return new EmbedLinksToStorageNode();
  }

  @GetMapping(value = "/children/{parentId}")
  @Transactional(readOnly = true)
  @Cacheable("lazy-tree")
  public Collection<NodeResource> populateChildren(@PathVariable Long parentId) {
    StorageNode parent = storageNodeRepository.findOne(parentId);
    return getValues(convertNodesToJson(parent.getChildren()));
  }

  @GetMapping(value = "/branch/{terminalNodeId}")
  @Transactional(readOnly = true)
  @Cacheable("lazy-tree")
  public Collection<NodeResource> populateBranch(@PathVariable Long terminalNodeId) {
    ArrayList<StorageNode> branch = new ArrayList<>();
    StorageNode node = storageNodeRepository.findOne(terminalNodeId);
    while (node != null) {
      branch.add(node);
      node = node.getParent();
    }
    Collections.reverse(branch); // Order : from root to leaf
    return Collections.singletonList(mergeEachBranchNodeWithSiblings(branch));
  }

  private NodeResource mergeEachBranchNodeWithSiblings(Collection<StorageNode> branch) {
    return mergeEachBranchNodeWithSiblings0(branch.iterator()).getRight();
  }

  private Pair<Long, NodeResource> mergeEachBranchNodeWithSiblings0(Iterator<StorageNode> branchItr) {
    Pair<Long, NodeResource> retVal = null;
    if (branchItr.hasNext()) {
      StorageNode sn = branchItr.next();
      Pair<Long, NodeResource> branchNode = convertNodeToJson(sn);
      final Pair<Long, NodeResource> nextBranchNode = mergeEachBranchNodeWithSiblings0(branchItr);
      if (nextBranchNode != null) {
        final Long nextBranchNodeId = nextBranchNode.getLeft();
        Collection<Pair<Long, NodeResource>> nextBranchNodeSiblings =
                convertNodesToJson(sn.getChildren()).stream().map(sibling ->
                        nextBranchNodeId.equals(sibling.getLeft())
                                ? nextBranchNode
                                : sibling)
                        .collect(Collectors.toCollection(ArrayList::new));
        branchNode = extendBranchNodeWithSiblings(sn, branchNode, nextBranchNodeSiblings);
      }
      retVal = branchNode;
    }
    return retVal;
  }

  private Pair<Long, NodeResource> extendBranchNodeWithSiblings(StorageNode sn,
                                                                Pair<Long, NodeResource> pair,
                                                                Collection<Pair<Long, NodeResource>> siblings)
  {
    NodeResource src = pair.getRight();
    BranchNodeResource retVal = new BranchNodeResource();
    retVal.setType(src.getType());
    retVal.setText(src.getText());
    retVal.setUploadTs(src.getUploadTs());
    retVal.setChildren(getValues(siblings));
    retVal.add(entityLinks.linkForSingleResource(StorageNode.class, sn.getId()).withSelfRel());
    return Pair.of(pair.getLeft(), retVal);
  }

  private Collection<Pair<Long, NodeResource>> convertNodesToJson(Collection<StorageNode> arg) {
    return arg.stream().map(this::convertNodeToJson).collect(Collectors.toCollection(ArrayList::new));
  }

  private Pair<Long, NodeResource> convertNodeToJson(StorageNode storageNode) {
    NodeResource retVal = new NodeResource();
    setCommonFields(retVal, storageNode);
    addStorageNodeLinks(storageNode, retVal);
    retVal.add(entityLinks.linkForSingleResource(StorageNode.class, storageNode.getId()).withSelfRel());
    return Pair.of(storageNode.getId(), retVal);
  }

  private void setCommonFields(NodeResource nodeRepr, StorageNode storageNode) {
    nodeRepr.setType(storageNode.getNodeType());
    nodeRepr.setText(storageNode.getText());
    nodeRepr.setUploadTs(storageNode.getUploadTs().toString());
  }

  private static void addStorageNodeLinks(StorageNode storageNode, ResourceSupport resource) {
    if (!isBranch(storageNode.getNodeType())) {
      if (storageNode.getNodeType() == NodeType.Image) {
        resource.add(linkTo(methodOn(Blobs.class).get(storageNode.getAquamarineId(),
                null, null, null, null, null)).withRel("as-image-fragment"));
      }
      resource.add(linkTo(methodOn(Blobs.class).getRaw(storageNode.getAquamarineId())).withRel("as-raw"));
    } else {
      resource.add(linkTo(methodOn(LazyTree.class).populateChildren(storageNode.getId())).withRel("lazy-children"));
    }
    resource.add(linkTo(methodOn(LazyTree.class).populateBranch(storageNode.getId())).withRel("lazy-branch"));
  }

  private static boolean isBranch(NodeType nodeType) {
    return nodeType == NodeType.Zip || nodeType == NodeType.Folder;
  }

  private static Collection<NodeResource> getValues(Collection<Pair<Long, NodeResource>> pairs) {
    return pairs.stream().map(Pair::getRight).collect(Collectors.toCollection(ArrayList::new));
  }

  private static class NodeResource extends ResourceSupport {
    private NodeType type;
    private String text;

    private String uploadTs;

    public NodeType getType() {
      return type;
    }

    public void setType(NodeType type) {
      this.type = type;
    }

    public String getText() {
      return text;
    }

    public void setText(String text) {
      this.text = text;
    }

    public String getUploadTs() {
      return uploadTs;
    }

    public void setUploadTs(String uploadTs) {
      this.uploadTs = uploadTs;
    }
  }

  private static class BranchNodeResource extends NodeResource {
    private Collection<NodeResource> children;

    public Collection<NodeResource> getChildren() {
      return children;
    }

    public void setChildren(Collection<NodeResource> children) {
      this.children = children;
    }
  }

  private static class EmbedLinksToStorageNode implements ResourceProcessor<Resource<StorageNode>> {
    @Override
    public Resource<StorageNode> process(Resource<StorageNode> resource) {
      addStorageNodeLinks(resource.getContent(), resource);
      return resource;
    }
  }
}
```

**Comment by gregturn** [comment]
Some suggestions:

. Move bean definitions outside of this controller. Controllers are created on demand, and can be transient. 
. Every endpoint that has a return type of `Collection<Resource>` should instead be using `Resources<T>`. When Jackson serializes the results, only things wrapped in `ResourceSupport` and its subtypes (`Resource`, `Resources`, and `PagedResources`) will form a proper HAL document. Any other return type will cause an improper rendering.
. Third, and not *really* related to your issue at hand--DON'T USE FIELD INJECTION. Use constructor injection instead. It's real simple and highly recommended by the Spring team. For more about this, please read http://olivergierke.de/2013/11/why-field-injection-is-evil/ by my manager.

**Comment by gehreleth** [comment]
Wrapped these collections. (Also moved bean definitions to `@Configuration` classes).

```
  @GetMapping(value = "/children/{parentId}")
  @Transactional(readOnly = true)
  @Cacheable("lazy-tree")
  public Resources<NodeResource> populateChildren(@PathVariable Long parentId) {
    StorageNode parent = storageNodeRepository.findOne(parentId);
    return new Resources<>(getValues(convertNodesToJson(parent.getChildren())));
  }

  @GetMapping(value = "/branch/{terminalNodeId}")
  @Transactional(readOnly = true)
  @Cacheable("lazy-tree")
  public Resources<NodeResource> populateBranch(@PathVariable Long terminalNodeId) {

    ArrayList<StorageNode> branch = new ArrayList<>();
    StorageNode node = storageNodeRepository.findOne(terminalNodeId);
    while (node != null) {
      branch.add(node);
      node = node.getParent();
    }
    Collections.reverse(branch); // Order : from root to leaf
    return new Resources<>(Collections.singletonList(mergeEachBranchNodeWithSiblings(branch)));
  }
```

Now I get this stacktrace. I don't understand the cause at this moment. I'm not using any kind of XML serialization in this project.

```
2018-01-21 09:57:16.033  WARN 10216 --- [nio-8080-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not marshal [Resources { content: [links: [<http://localhost:8080/emerald/api/hal/storage-node/26>;rel="self"]], links: [] }]: null; nested exception is javax.xml.bind.MarshalException
 - with linked exception:
[com.sun.istack.internal.SAXException2: unable to marshal type "org.crownjewels.emerald.controller.LazyTree$BranchNodeResource" as an element because it is missing an @XmlRootElement annotation]
2018-01-21 09:57:16.048 ERROR 10216 --- [nio-8080-exec-5] o.s.boot.web.support.ErrorPageFilter     : Forwarding to error page from request [/api/lazy-tree/branch/40] due to exception [getOutputStream() has already been called for this response]

java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at org.apache.catalina.connector.Response.getWriter(Response.java:621) ~[catalina.jar:9.0.0.M22]
        at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:227) ~[catalina.jar:9.0.0.M22]
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109) ~[servlet-api.jar:4.0.EDR-b01]
        at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109) ~[servlet-api.jar:4.0.EDR-b01]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.getWriter(OnCommittedResponseWrapper.java:149) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$SpelView.render(ErrorMvcAutoConfiguration.java:227) ~[spring-boot-autoconfigure-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M22]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M22]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:84) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) ~[spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M22]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M22]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710) ~[catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) ~[catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[catalina.jar:9.0.0.M22]
        at org.springframework.boot.web.support.ErrorPageFilter.handleErrorStatus(ErrorPageFilter.java:149) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:117) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:625) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:9.0.0.M22]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:9.0.0.M22]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498) [tomcat-coyote.jar:9.0.0.M22]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.0.M22]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796) [tomcat-coyote.jar:9.0.0.M22]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1372) [tomcat-coyote.jar:9.0.0.M22]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.0.M22]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.0.M22]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
```

**Comment by gehreleth** [comment]
UPD: If I add `produces = {MediaType.APPLICATION_JSON_VALUE, "application/hal+json"}` to mappings, this works, but nested links are marshalled as "_links" now, that's what I tried to avoid initially, because `@RepositoryRestResource` marshal them as "links" and I want to keep my frontend API more consistent.

**Comment by gregturn** [comment]
In a browser it will try XML before JSON. curl will go straight to JSON. This is classic Spring MVC. You can either use produces as you have done. Or simply append ".json" to the route. 

Regarding the output I'm confused. _links is HAL. links is not HAL, but instead a non standard representation.

**Comment by gehreleth** [comment]
I've already figured out how to get rid of this exception (I've set produces attribute in `@RestController`). However, I'm confused about what HAL. I've got a `@RepositoryRestResource`

```
@RepositoryRestResource(path = "storage-node", excerptProjection = IBrief.class)
public interface IStorageNodeRepository extends JpaRepository<StorageNode, Long> {
  @Query("FROM StorageNode sn WHERE sn.parent is null order by sn.uploadTs ASC")
  List<StorageNode> findAllRootNodes();
}
```

This is sample json+hal generated by it. It has "links" instead of "_links". I assumed that spring library will generate 100% pedantic json+hal and tried to mimic it.

```
{
  "links" : [ {
    "rel" : "first",
    "href" : "http://localhost:8080/emerald/api/hal/storage-node?page=0&size=20"
  }, {
    "rel" : "self",
    "href" : "http://localhost:8080/emerald/api/hal/storage-node{?page,size,sort,projection}"
  }, {
    "rel" : "next",
    "href" : "http://localhost:8080/emerald/api/hal/storage-node?page=1&size=20"
  }, {
    "rel" : "last",
    "href" : "http://localhost:8080/emerald/api/hal/storage-node?page=19&size=20"
  }, {
    "rel" : "profile",
    "href" : "http://localhost:8080/emerald/api/hal/profile/storage-node"
  }, {
    "rel" : "search",
    "href" : "http://localhost:8080/emerald/api/hal/storage-node/search"
  } ],
  "content" : [ {
    "text" : "src.zip",
    "nodeType" : "Zip",
    "links" : [ {
      "rel" : "self",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/26"
    }, {
      "rel" : "storageNode",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/26{?projection}"
    }, {
      "rel" : "parent",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/26/parent"
    }, {
      "rel" : "imageMetadata",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/26/imageMetadata"
    }, {
      "rel" : "children",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/26/children"
    } ]
  }, {
    "text" : "src",
    "nodeType" : "Folder",
    "links" : [ {
      "rel" : "self",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/27"
    }, {
      "rel" : "storageNode",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/27{?projection}"
    }, {
      "rel" : "parent",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/27/parent"
    }, {
      "rel" : "imageMetadata",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/27/imageMetadata"
    }, {
      "rel" : "children",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/27/children"
    } ]
  }, {
    "text" : "Documents",
    "nodeType" : "Folder",
    "links" : [ {
      "rel" : "self",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/28"
    }, {
      "rel" : "storageNode",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/28{?projection}"
    }, {
      "rel" : "parent",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/28/parent"
    }, {
      "rel" : "imageMetadata",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/28/imageMetadata"
    }, {
      "rel" : "children",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/28/children"
    } ]
  }, {
    "text" : "1.jpg",
    "nodeType" : "Image",
    "links" : [ {
      "rel" : "self",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/29"
    }, {
      "rel" : "storageNode",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/29{?projection}"
    }, {
      "rel" : "parent",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/29/parent"
    }, {
      "rel" : "imageMetadata",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/29/imageMetadata"
    }, {
      "rel" : "children",
      "href" : "http://localhost:8080/emerald/api/hal/storage-node/29/children"
    } ]
  }, 
/* ........ Irrelevant ............*/
 } ],
  "page" : {
    "size" : 20,
    "totalElements" : 381,
    "totalPages" : 20,
    "number" : 0
  }
}


```

**Comment by gregturn** [comment]
You are referring to a Spring Data repository. If this is Spring Data REST, you'll find that all the REST controllers leveraging scanned repositories return ResourceSupport-compatible types. When you don't, you get non-HAL stuff. 

Please read the spec if you don't believe me when I say that fragment up above isn't HAL. 

http://stateless.co/hal_specification.html

**Comment by gehreleth** [comment]
How to make Spring Data repository return valid HAL then? Did I overlook something in spring data repositories' initialization?

**Comment by gehreleth** [comment]
After giving it some thought, I've discovered this fragment.

```
@Bean
  public RepositoryRestConfigurer repositoryRestConfigurer() {
    return new RepositoryRestConfigurerAdapter() {
      @Override
      public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
        config.setBasePath("/api/hal");
        config.setDefaultMediaType(MediaType.APPLICATION_JSON_UTF8);
      }
    };
  }
```
Removing default media type did the job. I don't remember exactly under which circumstances I've added this. Maybe I had to explicitly say ;charset=utf8 in each response to deal with russian strings. You can close this issue.
